const german = {
  name: "Niemcy",
  entries: [
    { plate: "A", district: "Augsburg, Bawaria" },
    { plate: "AA", district: "Aalen i Ostalbkreis, Badenia-Wirtembergia" },
    { plate: "AB", district: "Aschaffenburg, Bawaria" },
    { plate: "ABG", district: "Altenburger Land, Turyngia" },
    { plate: "AC", district: "Aachen, Nadrenia Północna-Westfalia" },
    { plate: "AH", district: "Ahaus, Nadrenia Północna-Westfalia" },
    { plate: "AIB", district: "Bad Aibling, Bawaria" },
    { plate: "AIC", district: "Aichach-Friedberg, Bawaria" },
    { plate: "AE", district: "Auerbach, Saksonia" },
    { plate: "AK", district: "Altenkirchen (Westerwald), Nadrenia-Palatynat" },
    { plate: "AL", district: "Altena, Nadrenia Północna-Westfalia" },
    { plate: "ALF", district: "Alfeld, Dolna Saksonia" },
    { plate: "ALS", district: "Alsfeld, Hesja" },
    { plate: "ALZ", district: "Alzenau, Bawaria" },
    { plate: "AM", district: "Amberg, Bawaria" },
    { plate: "AN", district: "Ansbach, Bawaria" },
    { plate: "ANA", district: "Annaberg-Buchholz, Saksonia" },
    { plate: "ANG", district: "Angermünde, Brandenburgia" },
    { plate: "ANK", district: "Anklam, Meklemburgia-Pomorze Przednie" },
    { plate: "AO", district: "Altötting, Bawaria" },
    { plate: "AP", district: "Apolda i Weimarer Land, Turyngia" },
    { plate: "APD", district: "Apolda, Turyngia" },
    { plate: "AR", district: "Arnsberg, Nadrenia Północna-Westfalia" },
    { plate: "ARN", district: "Arnstadt, Turyngia" },
    { plate: "ART", district: "Artern, Turyngia" },
    { plate: "AS", district: "Amberg-Sulzbach, Bawaria" },
    { plate: "ASD", district: "Aschendorf, Dolna Saksonia" },
    {
      plate: "ASL",
      district: "Aschersleben-Staßfurter Landkreis, Saksonia-Anhalt",
    },
    { plate: "ASZ", district: "Aue-Schwarzenberg, Saksonia" },
    { plate: "AT", district: "Alten-Treptow, Meklemburgia-Pomorze Przednie" },
    { plate: "AU", district: "Aue, Saksonia" },
    { plate: "AUR", district: "Aurich, Dolna Saksonia" },
    { plate: "AW", district: "Ahrweiler, Nadrenia-Palatynat" },
    { plate: "AZ", district: "Alzey-Worms, Nadrenia-Palatynat" },
    { plate: "AZE", district: "Anhalt-Zerbst, Saksonia-Anhalt" },
    { plate: "B", district: "Berlin" },
    { plate: "BA", district: "Bamberg, Bawaria" },
    { plate: "BAD", district: "Baden-Baden, Badenia-Wirtembergia" },
    { plate: "BAR", district: "Eberswalde, Brandenburgia" },
    { plate: "BB", district: "Böblingen, Badenia-Wirtembergia" },
    { plate: "BBG", district: "Bernburg, Saksonia-Anhalt" },
    { plate: "BBL", district: "pojazdy admistracji landu Brandenburgia" },
    { plate: "BC", district: "Biberach, Badenia-Wirtembergia" },
    { plate: "BCH", district: "Buchen, Badenia-Wirtembergia" },
    { plate: "BD", district: "pojazdy administracji federalnej" },
    { plate: "BE", district: "Bechum, Nadrenia Północna-Westfalia" },
    { plate: "BED", district: "Brand-Erbisdorf, Saksonia" },
    { plate: "BEI", district: "Beilingries, Bawaria" },
    { plate: "BEL", district: "Blezig, Brandenburgia" },
    { plate: "BER", district: "Bernau, Brandenburgia" },
    { plate: "BF", district: "Burgsteinfurt, Nadrenia Północna-Westfalia" },
    { plate: "BG", district: "pojazdy straży granicznej" },
    { plate: "BGD", district: "Berchtesgaden, Bawaria" },
    { plate: "BGL", district: "Berchtesgardener Land, Bawaria" },
    { plate: "BH", district: "Bühl, Badenia-Wirtembergia" },
    { plate: "BI", district: "Bielefeld, Nadrenia Północna-Westfalia" },
    { plate: "BID", district: "Biedenkopf, Hesja" },
    { plate: "BIN", district: "Bingen, Nadrenia-Palatynat" },
    { plate: "BIR", district: "Birkenfeld, Nadrenia-Palatynat" },
    { plate: "BIT", district: "Bitburg-Prüm, Nadrenia-Palatynat" },
    { plate: "BIW", district: "Bischofswerda, Saksonia" },
    { plate: "BK", district: "Bicknang, Badenia-Wirtembergia" },
    { plate: "BKS", district: "Bernkastel, Nadrenia-Palatynat" },
    {
      plate: "BL",
      district: "Balingen i Zollernalbkreis, Badenia-Wirtembergia",
    },
    { plate: "BLB", district: "Bad Berleburg, Nadrenia Północna-Westfalia" },
    { plate: "BLK", district: "Burgenlandkreis, Saksonia-Anhalt" },
    {
      plate: "BM",
      district: "Bergheim i Erftkreis, Nadrenia Północna-Westfalia",
    },
    { plate: "BN", district: "Bonn, Nadrenia Północna-Westfalia" },
    { plate: "BNA", district: "Borna, Saksonia" },
    { plate: "BO", district: "Bochum, Nadrenia Północna-Westfalia" },
    { plate: "BO", district: "Bördekreis, Saksonia-Anhalt" },
    { plate: "BOG", district: "Bogen, Bawaria" },
    { plate: "BOH", district: "Bocholt, Nadrenia Północna-Westfalia" },
    { plate: "BOR", district: "Borken, Nadrenia Północna-Westfalia" },
    { plate: "BOT", district: "Bottrop, Nadrenia Północna-Westfalia" },
    { plate: "BP", district: "pojazdy poczty federalnej" },
    { plate: "BR", district: "Bruchsal, Badenia-Wirtembergia" },
    { plate: "BRA", district: "Unterweser i Wesermarsch, Dolna Saksonia" },
    { plate: "BRB", district: "Brandenburg, Brandenburgia" },
    { plate: "BRG", district: "Burg, Saksonia-Anhalt" },
    { plate: "BRI", district: "Brilon, Nadrenia Północna-Westfalia" },
    { plate: "BRK", district: "Bad Brückenau, Bawaria" },
    { plate: "BRL", district: "Braunlage, Dolna Saksonia" },
    { plate: "BRV", district: "Bremervörde, Dolna Saksonia" },
    { plate: "BS", district: "Braunschweig, Dolna Saksonia" },
    { plate: "BSB", district: "Bersenbrück, Dolna Saksonia" },
    { plate: "BSK", district: "Beeskow, Brandenburgia" },
    { plate: "BT", district: "Bayreuth, Bawaria" },
    { plate: "BTF", district: "Bitterfeld, Saksonia-Anhalt" },
    { plate: "BU", district: "Burgdorf, Dolna Saksonia" },
    { plate: "BUD", district: "Büdingen, Hesja" },
    { plate: "BUL", district: "Burglengenfeld, Bawaria" },
    { plate: "BUR", district: "Buren, Nadrenia Północna-Westfalia" },
    { plate: "BUS", district: "Büsingen i Konstanz, Badenia-Wirtembergia" },
    { plate: "BUZ", district: "Bützow, Meklemburgia-Pomorze Przednie" },
    { plate: "BW", district: "pojazdy administracji żeglugowej i morskiej" },
    {
      plate: "BWL",
      district: "pojazdy administracji landu Badenia-Wirtembergia",
    },
    { plate: "BYL", district: "pojazdy administracji landu Bawaria" },
    { plate: "BZ", district: "Bautzen, Saksonia" },
    { plate: "BZA", district: "Bergzabern, Nadrenia-Palatynat" },
    { plate: "C", district: "Chemnitz, Saksonia" },
    { plate: "CA", district: "Calau, Brandenburgia" },
    { plate: "CAS", district: "Castrop-Rauxel, Nadrenia Północna-Westfalia" },
    { plate: "CB", district: "Cottbus, Brandenburgia" },
    { plate: "CE", district: "Celle, Dolna Saksonia" },
    { plate: "CHA", district: "Cham, Bawaria" },
    { plate: "CHL", district: "Chemnitzer Land, Kreis Glochau, Saksonia" },
    { plate: "CLP", district: "Cloppenburg, Dolna Saksonia" },
    { plate: "CLZ", district: "Clausthal-Zellerfeld, Dolna Saksonia" },
    { plate: "CO", district: "Coburg, Bawaria" },
    { plate: "COC", district: "Cochem-Zell, Nadrenia-Palatynat" },
    { plate: "COE", district: "Coesfeld, Nadrenia Północna-Westfalia" },
    { plate: "CR", district: "Crailsheim, Badenia-Wirtembergia" },
    { plate: "CT", district: "Cottbus, Saksonia" },
    { plate: "CUX", district: "Cuxhaven, Dolna Saksonia" },
    { plate: "CW", district: "Calw, Badenia-Wirtembergia" },
    { plate: "D", district: "Düsseldorf, Nadrenia Północna-Westfalia" },
    { plate: "DA", district: "Darmstadt i Darmstadt-Dieburg, Hesja" },
    { plate: "DAH", district: "Dachau, Bawaria" },
    { plate: "DAN", district: "Lüchow-Dannenberg, Dolna Saksonia" },
    { plate: "DAU", district: "Daun, Nadrenia-Palatynat" },
    { plate: "DB", district: "pojazdy administracji niemieckich kolei" },
    { plate: "DBR", district: "Bad Doberan, Meklemburgia-Pomorze Przednie" },
    { plate: "DD", district: "Drezno, Saksonia" },
    { plate: "DE", district: "Dessau, Saksonia-Anhalt" },
    { plate: "DEG", district: "Deggendorf, Bawaria" },
    { plate: "DEL", district: "Delmenhorst, Dolna Saksonia" },
    { plate: "DG", district: "Donaueschingen, Badenia-Wirtembergia" },
    { plate: "DGF", district: "Dingolfing-Landau, Bawaria" },
    { plate: "DH", district: "Diepholz, Dolna Saksonia" },
    { plate: "DI", district: "Dieburg, Hesja" },
    { plate: "DIL", district: "Dillenburg, Hesja" },
    { plate: "DIN", district: "Dinslaken, Nadrenia Północna-Westfalia" },
    { plate: "DIZ", district: "Diez, Nadrenia-Palatynat" },
    { plate: "DKB", district: "Dinkelsbühl, Bawaria" },
    { plate: "DL", district: "Döbeln, Saksonia" },
    { plate: "DLG", district: "Dillingen an der Donau, Bawaria" },
    { plate: "DM", district: "Demmin, Meklemburgia-Pomorze Przednie" },
    { plate: "DN", district: "Düren, Nadrenia Północna-Westfalia" },
    { plate: "DO", district: "Dortmund, Nadrenia Północna-Westfalia" },
    { plate: "DON", district: "Donau-Ries, Bawaria" },
    { plate: "DS", district: "Donaueschingen, Badenia-Wirtembergia" },
    { plate: "DT", district: "Detmold i Lippe, Nadrenia Północna-Westfalia" },
    { plate: "DU", district: "Duisburg, Nadrenia Północna-Westfalia" },
    { plate: "DUD", district: "Duderstadt, Dolna Saksonia" },
    { plate: "DUW", district: "Bad Dürkheim i Weinstraße, Nadrenia-Palatynat" },
    { plate: "DW", district: "Dippoldiswalde i Weißeritzkreis, Saksonia" },
    { plate: "DZ", district: "Delitzsch, Saksonia" },
    { plate: "E", district: "Essen, Nadrenia Północna-Westfalia" },
    { plate: "EA", district: "Eisenach, Turyngia" },
    { plate: "EB", district: "Eilenburg, Saksonia" },
    { plate: "EBE", district: "Ebersberg, Bawaria" },
    { plate: "EBN", district: "Ebern, Bawaria" },
    { plate: "EBS", district: "Ebermannstadt, Bawaria" },
    { plate: "ECK", district: "Eckernförde, Szlezwik-Holsztyn" },
    { plate: "ED", district: "Erding, Bawaria" },
    { plate: "EE", district: "Elbe-Elster, Brandenburgia" },
    { plate: "EF", district: "Erfurt, Turyngia" },
    { plate: "EG", district: "Eggenfelden, Bawaria" },
    { plate: "EH", district: "Eisenhüttenstadt, Brandenburgia" },
    { plate: "EHI", district: "Ehingen, Badenia-Wirtembergia" },
    { plate: "EI", district: "Eichstätt, Bawaria" },
    { plate: "EIC", district: "Eichsfeld, Turyngia" },
    { plate: "EIH", district: "Eichstätt, Bawaria" },
    { plate: "EIL", district: "Eisleben, Saksonia-Anhalt" },
    { plate: "EIN", district: "Einbeck, Dolna Saksonia" },
    { plate: "EIS", district: "Eisenberg" },
    { plate: "EL", district: "Emsland, Dolna Saksonia" },
    { plate: "EM", district: "Emmendingen, Badenia-Wirtembergia" },
    { plate: "EMD", district: "Emden, Dolna Saksonia" },
    {
      plate: "EMS",
      district: "Bad Ems i Rhein-Lahn-Kreis, Nadrenia-Palatynat",
    },
    { plate: "EN", district: "Ennepe-Ruhr-Kreis, Nadrenia Północna-Westfalia" },
    { plate: "ER", district: "Erlangen, Bawaria" },
    { plate: "ERB", district: "Erbach i Oldenwaldkreis, Hesja" },
    { plate: "ERH", district: "Erlangen-Höchstadt, Bawaria" },
    { plate: "ERK", district: "Erkelenz, Nadrenia Północna-Westfalia" },
    { plate: "ES", district: "Esslingen, Badenia-Wirtembergia" },
    { plate: "ESA", district: "Eisenach, Turyngia" },
    { plate: "ESB", district: "Eschenbach, Bawaria" },
    { plate: "ESW", district: "Eschwege i Werra-Meißner-Kreis, Hesja" },
    { plate: "EU", district: "Euskirchen, Nadrenia Północna-Westfalia" },
    { plate: "EUT", district: "Eutin, Szlezwik-Holsztyn" },
    { plate: "EW", district: "Eberswalde, Brandenburgia" },
    { plate: "F", district: "Frankfurt nad Menem, Hesja" },
    { plate: "FAL", district: "Fallingbostel, Nadrenia Północna-Westfalia" },
    { plate: "FB", district: "Hessen i Wetteraukreis, Hesja" },
    { plate: "FD", district: "Fulda, Hesja" },
    { plate: "FDB", district: "Friedberg bei Augsburg, Bawaria" },
    { plate: "FDS", district: "Freudenstadt, Badenia-Wirtembergia" },
    { plate: "FEU", district: "Feuchtwangen, Bawaria" },
    { plate: "FF", district: "Frankfurt nad Odrą, Brandenburgia" },
    { plate: "FFB", district: "Fürstenfeldbruck, Bawaria" },
    { plate: "FG", district: "Freiberg, Saksonia" },
    { plate: "FH", district: "dzielnica Höchst (Frankfurt nad Menem), Hesja" },
    { plate: "FI", district: "Finsterwalde, Brandenburgia" },
    { plate: "FKB", district: "Frankenberg, Hesja" },
    { plate: "FL", district: "Flensburg, Szlezwik-Holsztyn" },
    { plate: "FLO", district: "Flöha, Saksonia" },
    {
      plate: "FN",
      district: "Friedrichshafen i Bodenseekreis, Badenia-Wirtembergia",
    },
    { plate: "FO", district: "Forchheim, Bawaria" },
    { plate: "FOR", district: "Forst, Brandenburgia" },
    {
      plate: "FR",
      district:
        "Freiburg im Breisgau i Breisgau-Hochschwarzwald, Badenia-Wirtembergia",
    },
    { plate: "FRG", district: "Freyung-Grafenau, Bawaria" },
    { plate: "FRI", district: "Friesland, Dolna Saksonia" },
    { plate: "FRW", district: "Bad Freienwalde, Brandenburgia" },
    { plate: "FS", district: "Freising, Bawaria" },
    { plate: "FT", district: "Pfalz, Nadrenia-Palatynat" },
    { plate: "FTL", district: "Freital, Saksonia" },
    { plate: "FU", district: "Fürth, Bawaria" },
    { plate: "FUS", district: "Füssen, Bawaria" },
    { plate: "FW", district: "Fürstenwalde, Brandenburgia" },
    { plate: "FZ", district: "Fritzlar, Hesja" },
    { plate: "G", district: "Gera, Turyngia" },
    { plate: "GA", district: "Gardelegen, Saksonia-Anhalt" },
    { plate: "GAN", district: "Bad Gandersheim, Dolna Saksonia" },
    { plate: "GAP", district: "Garmisch-Partenkirchen, Bawaria" },
    { plate: "GC", district: "Glauchau i Chemnitzer Land, Saksonia" },
    { plate: "GD", district: "Gmünd, Badenia-Wirtembergia" },
    { plate: "GDB", district: "Gadesbusch, Meklemburgia-Pomorze Przednie" },
    { plate: "GE", district: "Gelsenkirchen, Nadrenia Północna-Westfalia" },
    { plate: "GEL", district: "Geldern, Nadrenia Północna-Westfalia" },
    { plate: "GEM", district: "Gemünden, Bawaria" },
    { plate: "GEO", district: "Gerolzhofen, Bawaria" },
    { plate: "GER", district: "Germersheim, Nadrenia-Palatynat" },
    { plate: "GF", district: "Gifhorn, Dolna Saksonia" },
    { plate: "GG", district: "Groß-Gerau, Hesja" },
    { plate: "GHA", district: "Geithain, Saksonia" },
    { plate: "GHC", district: "Gräfenhainichen, Saksonia-Anhalt" },
    { plate: "GI", district: "Gießen, Hesja" },
    { plate: "GK", district: "Geilenkirchen, Nadrenia Północna-Westfalia" },
    {
      plate: "GL",
      district:
        "Bergisch-Gladbach i Rheinisch-Bergischer Kreis, Nadrenia Północna-Westfalia",
    },
    { plate: "GLA", district: "Gladbeck, Nadrenia Północna-Westfalia" },
    {
      plate: "GM",
      district:
        "Gummersbach i Oberbergischer Kreis, Nadrenia Północna-Westfalia",
    },
    { plate: "GMN", district: "Grimmen, Meklemburgia-Pomorze Przednie" },
    { plate: "GN", district: "Gelnhausen, Hesja" },
    { plate: "GNT", district: "Genthin, Saksonia-Anhalt" },
    { plate: "GO", district: "Göttingen, Dolna Saksonia" },
    { plate: "GOA", district: "St Goar, Nadrenia-Palatynat" },
    { plate: "GOH", district: "St Goarshausen, Nadrenia-Palatynat" },
    { plate: "GP", district: "Göppingen, Badenia-Wirtembergia" },
    { plate: "GR", district: "Görlitz, Saksonia" },
    { plate: "GRA", district: "Grafenau, Bawaria" },
    { plate: "GRH", district: "Grossenheim" },
    { plate: "GRI", district: "Griesbach, Bawaria" },
    { plate: "GRM", district: "Grimma, Saksonia" },
    { plate: "GRS", district: "Gransee, Brandenburgia" },
    { plate: "GRZ", district: "Greiz, Turyngia" },
    { plate: "GS", district: "Goslar, Dolna Saksonia" },
    { plate: "GT", district: "Gütersloh, Nadrenia Północna-Westfalia" },
    { plate: "GTH", district: "Gotha, Turyngia" },
    { plate: "GU", district: "Güstrow, Meklemburgia-Pomorze Przednie" },
    { plate: "GUB", district: "Guben, Brandenburgia" },
    { plate: "GUN", district: "Gunzenhausen, Bawaria" },
    { plate: "GV", district: "Gravenbroich, Nadrenia Północna-Westfalia" },
    { plate: "GVM", district: "Grevesmühlen, Meklemburgia-Pomorze Przednie" },
    { plate: "GW", district: "Greifswald Land, Meklemburgia-Pomorze Przednie" },
    { plate: "GZ", district: "Günzburg, Bawaria" },
    { plate: "H", district: "Hanower, Dolna Saksonia" },
    { plate: "HA", district: "Hagen, Nadrenia Północna-Westfalia" },
    { plate: "HAB", district: "Hammelburg, Bawaria" },
    { plate: "HAL", district: "Halle, Saksonia-Anhalt" },
    { plate: "HAM", district: "Hamm, Nadrenia Północna-Westfalia" },
    { plate: "HAS", district: "Haßberge, Bawaria" },
    { plate: "HB", district: "Hansestadt Bremen" },
    { plate: "HBN", district: "Hildburghausen, Turyngia" },
    { plate: "HBS", district: "Halberstadt, Saksonia-Anhalt" },
    { plate: "HC", district: "Hainichen, Saksonia" },
    { plate: "HCH", district: "Hechingen, Badenia-Wirtembergia" },
    {
      plate: "HD",
      district: "Heidelberg i Rhein-Neckar-Kreis, Badenia-Wirtembergia",
    },
    { plate: "HDH", district: "Heidenheim, Badenia-Wirtembergia" },
    { plate: "HDL", district: "Haldensleben, Saksonia-Anhalt" },
    { plate: "HE", district: "Helmstedt, Dolna Saksonia" },
    { plate: "HEB", district: "Hersbruck, Bawaria" },
    { plate: "HEF", district: "Hersfeld-Rotenburg, Hesja" },
    { plate: "HEI", district: "Heide i Dithmarschen, Szlezwik-Holsztyn" },
    { plate: "HEL", district: "pojazdy administracji landu Hesja" },
    { plate: "HER", district: "Herne, Nadrenia Północna-Westfalia" },
    { plate: "HET", district: "Hettstedt, Saksonia-Anhalt" },
    { plate: "HF", district: "Herford, Nadrenia Północna-Westfalia" },
    {
      plate: "HG",
      district: "Bad Homburg vor der Höhe i Hochtaunuskreis, Hesja",
    },
    { plate: "HGN", district: "Hagenow, Meklemburgia-Pomorze Przednie" },
    {
      plate: "HGW",
      district: "Hansestadt Greifswald, Meklemburgia-Pomorze Przednie",
    },
    { plate: "HH", district: "Hansestadt Hamburg" },
    { plate: "HHM", district: "Hohenmölsen, Saksonia-Anhalt" },
    { plate: "HI", district: "Hildesheim, Dolna Saksonia" },
    { plate: "HIG", district: "Heiligenstadt, Turyngia" },
    { plate: "HIP", district: "Hilpoltstein, Bawaria" },
    { plate: "HL", district: "Hansestadt Lübeck" },
    { plate: "HM", district: "Hameln-Pyrmont, Dolna Saksonia" },
    { plate: "HMU", district: "Hanoversch Münden, Dolna Saksonia" },
    { plate: "HN", district: "Heilbronn, Badenia-Wirtembergia" },
    { plate: "HO", district: "Hof, Bawaria" },
    { plate: "HOG", district: "Hofgeismar, Hesja" },
    { plate: "HOH", district: "Hofheim, Bawaria" },
    { plate: "HOL", district: "Holzminden, Dolna Saksonia" },
    { plate: "HOM", district: "Homburg i Saar-Pfalz-Kreis, Saara" },
    { plate: "HOR", district: "Horb, Badenia-Wirtembergia" },
    { plate: "HOS", district: "Höchstadt, Bawaria" },
    { plate: "HOT", district: "Hohenstein-Ernstthal, Saksonia" },
    {
      plate: "HP",
      district: "Heppenheim an der Bergstraße i Bergstraße, Hesja",
    },
    { plate: "HR", district: "Homberg i Schwalm-Eder-Kreis, Hesja" },
    {
      plate: "HRO",
      district: "Hansestadt Rostock, Meklemburgia-Pomorze Przednie",
    },
    { plate: "HS", district: "Heinsberg, Nadrenia Północna-Westfalia" },
    {
      plate: "HSK",
      district: "Hochsauerlandkreis, Nadrenia Północna-Westfalia",
    },
    {
      plate: "HST",
      district: "Hansestadt Stralsund, Meklemburgia-Pomorze Przednie",
    },
    { plate: "HU", district: "Hanau i Main-Kinzig-Kreis, Hesja" },
    { plate: "HUN", district: "Hünfeld, Szlezwik-Holsztyn" },
    { plate: "HUS", district: "Husum, Szlezwik-Holsztyn" },
    { plate: "HV", district: "Havelberg, Saksonia-Anhalt" },
    { plate: "HVL", district: "Havelland, Brandenburgia" },
    { plate: "HW", district: "Halle Westfalen, Nadrenia Północna-Westfalia" },
    {
      plate: "HWI",
      district: "Hansestadt Wismar, Meklemburgia-Pomorze Przednie",
    },
    { plate: "HX", district: "Höxter, Nadrenia Północna-Westfalia" },
    { plate: "HY", district: "Hoyerswerda, Saksonia" },
    { plate: "HZ", district: "Herzberg, Brandenburgia" },
    { plate: "IGB", district: "Stadt St Ingbert i Saar-Pfalz-Kreis, Saara" },
    { plate: "IK", district: "Ilm-Kreis, Turyngia" },
    { plate: "IL", district: "Ilmenau, Turyngia" },
    { plate: "ILL", district: "Illertissen, Bawaria" },
    { plate: "IN", district: "Ingolstadt, Bawaria" },
    { plate: "IS", district: "Iserlohn, Nadrenia Północna-Westfalia" },
    { plate: "IZ", district: "Itzehoe i Steinburg, Szlezwik-Holsztyn" },
    { plate: "J", district: "Jena, Turyngia" },
    { plate: "JB", district: "Jüterbog, Brandenburgia" },
    { plate: "JE", district: "Jessen, Saksonia-Anhalt" },
    { plate: "JEV", district: "Jever, Dolna Saksonia" },
    { plate: "JL", district: "Jerichower Land, Saksonia-Anhalt" },
    { plate: "JUL", district: "Jülich, Nadrenia Północna-Westfalia" },
    { plate: "K", district: "Kolonia, Nadrenia Północna-Westfalia" },
    { plate: "KA", district: "Karlsruhe, Badenia-Wirtembergia" },
    { plate: "KAR", district: "Karlstadt, Bawaria" },
    { plate: "KB", district: "Korbach i Waldeck-Frankenberg, Hesja" },
    { plate: "KC", district: "Kronach, Bawaria" },
    { plate: "KE", district: "Allgäu, Bawaria" },
    { plate: "KEH", district: "Kelheim, Bawaria" },
    { plate: "KEL", district: "Kehl, Badenia-Wirtembergia" },
    { plate: "KEM", district: "Kemnath, Bawaria" },
    { plate: "KF", district: "Kaufbeuren, Bawaria" },
    { plate: "KG", district: "Bad Kissingen, Bawaria" },
    { plate: "KH", district: "Bad Kreuznach, Nadrenia-Palatynat" },
    { plate: "KI", district: "Kilonia, Szlezwik-Holsztyn" },
    {
      plate: "KIB",
      district: "Kirchheimbolanden i Donnersbergkreis, Nadrenia-Palatynat",
    },
    { plate: "KK", district: "Kempen-Krefeld, Nadrenia Północna-Westfalia" },
    { plate: "KL", district: "Kaiserslauten, Nadrenia-Palatynat" },
    { plate: "KLE", district: "Kleve, Nadrenia Północna-Westfalia" },
    { plate: "KLT", district: "Klingental, Saksonia" },
    { plate: "KLZ", district: "Klötze, Saksonia-Anhalt" },
    { plate: "KM", district: "Kamenz, Saksonia" },
    { plate: "KN", district: "Konstancja, Badenia-Wirtembergia" },
    { plate: "KO", district: "Koblencja, Nadrenia-Palatynat" },
    { plate: "KON", district: "Kötzting, Bawaria" },
    { plate: "KOT", district: "Köthen, Saksonia-Anhalt" },
    { plate: "KOZ", district: "Kotzting" },
    { plate: "KR", district: "Krefeld, Nadrenia Północna-Westfalia" },
    { plate: "KRU", district: "Krumbach, Bawaria" },
    { plate: "KS", district: "Kassel, Hesja" },
    { plate: "KT", district: "Kitzingen, Bawaria" },
    { plate: "KU", district: "Kulmbach, Bawaria" },
    {
      plate: "KUN",
      district: "Küzelsau i Hohenlohekreis, Badenia-Wirtembergia",
    },
    { plate: "KUS", district: "Kusel, Nadrenia-Palatynat" },
    { plate: "KW", district: "Königs-Wusterhausen, Brandenburgia" },
    { plate: "KY", district: "Kyritz, Brandenburgia" },
    { plate: "KYF", district: "Kyffhäuserkreis, Turyngia" },
    { plate: "L", district: "Lipsk, Saksonia" },
    { plate: "LA", district: "Landshut, Bawaria" },
    { plate: "LAN", district: "Landau Isar, Bawaria" },
    { plate: "LAT", district: "Lauterbach, Hesja" },
    {
      plate: "LAU",
      district: "Lauf an der Pegnitz i Nürnberger Land, Bawaria",
    },
    { plate: "LB", district: "Ludwigsburg, Badenia-Wirtembergia" },
    { plate: "LBS", district: "Lobenstein, Turyngia" },
    { plate: "LBZ", district: "Lübz, Meklemburgia-Pomorze Przednie" },
    { plate: "LC", district: "Luckau, Brandenburgia" },
    { plate: "LD", district: "Landau in der Pfalz, Nadrenia-Palatynat" },
    { plate: "LDK", district: "Lahn-Dill-Kreis, Hesja" },
    { plate: "LDS", district: "Landkreis Dahme-Spreewald, Brandenburgia" },
    { plate: "LE", district: "Lemgo, Nadrenia Północna-Westfalia" },
    { plate: "LEO", district: "Leonberg, Badenia-Wirtembergia" },
    { plate: "LER", district: "Leer (Ostfriesland), Dolna Saksonia" },
    { plate: "LEV", district: "Leverkusen, Nadrenia Północna-Westfalia" },
    { plate: "LF", district: "Laufen, Bawaria" },
    { plate: "LG", district: "Lüneburg, Dolna Saksonia" },
    { plate: "LH", district: "Lüdinghausen, Nadrenia Północna-Westfalia" },
    { plate: "LI", district: "Lindau (Bodensee), Bawaria" },
    { plate: "LIB", district: "Bad Liebenwerda, Brandenburgia" },
    { plate: "LIF", district: "Lichtenfels, Bawaria" },
    { plate: "LIN", district: "Lingen, Dolna Saksonia" },
    { plate: "LIP", district: "Lippe, Nadrenia Północna-Westfalia" },
    { plate: "LK", district: "Lübbecke, Nadrenia Północna-Westfalia" },
    { plate: "LL", district: "Landsberg am Lech, Bawaria" },
    { plate: "LM", district: "Limburg-Weilburg, Hesja" },
    { plate: "LN", district: "Lübben, Brandenburgia" },
    { plate: "LO", district: "Lörrach, Badenia-Wirtembergia" },
    { plate: "LOB", district: "Löbau, Saksonia" },
    { plate: "LOH", district: "Lohr am Main, Bawari" },
    { plate: "LOS", district: "Landkreis Oder-Spree, Brandenburgia" },
    { plate: "LP", district: "Lippstadt, Nadrenia Północna-Westfalia" },
    { plate: "LR", district: "Lahr, Badenia-Wirtembergia" },
    { plate: "LS", district: "Lüdenscheid, Nadrenia Północna-Westfalia" },
    { plate: "LSA", district: "pojazdy administracji landu Saksonia-Anhalt" },
    { plate: "LSN", district: "pojazdy administracji landu Saksonia" },
    { plate: "LSZ", district: "Bad Langensalza, Turyngia" },
    { plate: "LU", district: "Ludwigshafen am Rhein, Nadrenia-Palatynat" },
    { plate: "LUD", district: "Lüdenscheid, Nadrenia Północna-Westfalia" },
    { plate: "LUK", district: "Luckenwalde, Brandenburgia" },
    { plate: "LUN", district: "Lünen, Nadrenia Północna-Westfalia" },
    { plate: "LWL", district: "Ludwigslust, Meklemburgia-Pomorze Przednie" },
    { plate: "M", district: "Monachium, Bawaria" },
    { plate: "MA", district: "Mannheim, Badenia-Wirtembergia" },
    { plate: "MAB", district: "Marienberg, Saksonia" },
    { plate: "MAI", district: "Mainburg, Bawaria" },
    { plate: "MAK", district: "Marktredwitz, Bawaria" },
    { plate: "MAL", district: "Mallersdorf, Bawaria" },
    { plate: "MAR", district: "Marktheidenfeld, Bawaria" },
    { plate: "MB", district: "Miesbach, Bawaria" },
    { plate: "MC", district: "Malchin, Meklemburgia-Pomorze Przednie" },
    { plate: "MD", district: "Magdeburg, Saksonia-Anhalt" },
    { plate: "ME", district: "Mettmann, Nadrenia Północna-Westfalia" },
    { plate: "MED", district: "Meldorf, Szlezwik-Holsztyn" },
    { plate: "MEG", district: "Melsungen, Hesja" },
    { plate: "MEI", district: "Meissen, Saksonia" },
    { plate: "MEK", district: "Mittlerer Erzgebirgskreis, Saksonia" },
    { plate: "MEL", district: "Melle, Dolna Saksonia" },
    { plate: "MEP", district: "Meppen, Dolna Saksonia" },
    { plate: "MER", district: "Merseburg, Saksonia-Anhalt" },
    { plate: "MES", district: "Meschede, Nadrenia Północna-Westfalia" },
    { plate: "MET", district: "Mellrichstadt, Bawaria" },
    { plate: "MG", district: "Mönchengladbach, Nadrenia Północna-Westfalia" },
    { plate: "MGH", district: "Bad Mergentheim, Badenia-Wirtembergia" },
    { plate: "MGN", district: "Meiningen, Turyngia" },
    {
      plate: "MH",
      district: "Mülheim an der Ruhr, Nadrenia Północna-Westfalia",
    },
    { plate: "MHL", district: "Mühlhausen" },
    { plate: "MI", district: "Minden-Lübbecke, Nadrenia Północna-Westfalia" },
    { plate: "MIL", district: "Miltenberg, Bawaria" },
    { plate: "MK", district: "Märkischer Kreis, Nadrenia Północna-Westfalia" },
    { plate: "ML", district: "Mansfelder Land, Saksonia-Anhalt" },
    { plate: "MM", district: "Memmingen, Bawaria" },
    { plate: "MN", district: "Mindelheim i Unterallgäu, Bawaria" },
    { plate: "MO", district: "Moers, Nadrenia Północna-Westfalia" },
    { plate: "MOD", district: "Marktoberdorf, Bawaria" },
    { plate: "MOL", district: "Märkisch-Oderland, Brandenburgia" },
    { plate: "MON", district: "Monschau, Nadrenia Północna-Westfalia" },
    {
      plate: "MOS",
      district: "Mosbach i Neckar-Odenwald-Kreis, Badenia-Wirtembergia",
    },
    { plate: "MQ", district: "Merseburg-Querfurt, Saksonia-Anhalt" },
    { plate: "MR", district: "Marburg-Biedenkopf, Hesja" },
    { plate: "MS", district: "Münster, Nadrenia Północna-Westfalia" },
    { plate: "MSP", district: "Main-Spessart-Kreis, Bawaria" },
    {
      plate: "MST",
      district: "Mecklenburg-Strelitz, Meklemburgia-Pomorze Przednie",
    },
    { plate: "MT", district: "Montabaur, Nadrenia-Palatynat" },
    { plate: "MTK", district: "Main-Taunus-Kreis, Hesja" },
    { plate: "MTL", district: "Muldentalkreis, Saksonia" },
    { plate: "MU", district: "Mühldorf am Inn, Bawaria" },
    { plate: "MUB", district: "Münchberg, Bawaria" },
    { plate: "MUL", district: "Müllheim, Badenia-Wirtembergia" },
    { plate: "MUN", district: "Münsingen, Badenia-Wirtembergia" },
    { plate: "MUR", district: "Müritz, Meklemburgia-Pomorze Przednie" },
    {
      plate: "MVL",
      district: "pojazdy administracji landu Meklemburgia-Pomorze Przednie",
    },
    { plate: "MW", district: "Mittweida, Saksonia" },
    { plate: "MY", district: "Mayen, Nadrenia-Palatynat" },
    { plate: "MYK", district: "Mayen-Koblenz, Nadrenia-Palatynat" },
    { plate: "MZ", district: "Moguncja i Mainz-Bingen, Nadrenia-Palatynat" },
    { plate: "MZG", district: "Merzig-Wadern, Saara" },
    { plate: "N", district: "Nürnberg, Bawaria" },
    { plate: "NAB", district: "Nabburg, Bawaria" },
    { plate: "NAI", district: "Naila, Bawaria" },
    { plate: "NAU", district: "Nauen, Brandenburgia" },
    { plate: "NB", district: "Neubrandenburg, Meklemburgia-Pomorze Przednie" },
    {
      plate: "ND",
      district: "Neuberg an der Donau i Neuberg-Schrobenhausen, Bawaria",
    },
    { plate: "NDH", district: "Nordhausen, Turyngia" },
    { plate: "NE", district: "Neuss, Nadrenia Północna-Westfalia" },
    {
      plate: "NEA",
      district: "Neustadt an der Aisch i Bad Windsheim, Bawaria",
    },
    { plate: "NEB", district: "Nebra, Saksonia-Anhalt" },
    { plate: "NEC", district: "Neustadt Coburg, Bawaria" },
    { plate: "NEN", district: "Neunburg, Bawaria" },
    {
      plate: "NES",
      district: "Bad Neustadt an der Saale i Rhön-Grabfeld, Bawaria",
    },
    { plate: "NEU", district: "Neustadt Schwarzwald, Badenia-Wirtembergia" },
    { plate: "NEW", district: "Neustadt an der Waldnaab, Bawaria" },
    { plate: "NF", district: "Nordfriesland, Szlezwik-Holsztyn" },
    { plate: "NH", district: "Neuhaus an der Rennweg, Turyngia" },
    { plate: "NI", district: "Nienberg (Weser), Dolna Saksonia" },
    { plate: "NIB", district: "Niebüll, Szlezwik-Holsztyn" },
    { plate: "NK", district: "NeunkirchenSaar, Saara" },
    { plate: "NL", district: "pojazdy administracji landu Dolna Saksonia" },
    { plate: "NM", district: "Neumarkt in der Oberpfalz, Bawaria" },
    { plate: "NMB", district: "Naumberg, Saksonia-Anhalt" },
    { plate: "NMS", district: "Neumünster, Szlezwik-Holsztyn" },
    { plate: "NO", district: "Nördlingen, Bawaria" },
    {
      plate: "NOH",
      district: "Nordhorn i Grafschaft Bentheim, Dolna Saksonia",
    },
    { plate: "NOL", district: "Niederschlesischer Oberlausitzkreis, Saksonia" },
    { plate: "NOM", district: "Northeim, Dolna Saksonia" },
    { plate: "NOR", district: "Norden, Dolna Saksonia" },
    { plate: "NP", district: "Neuruppin, Brandenburgia" },
    { plate: "NR", district: "Neuwied am Rhein, Nadrenia-Palatynat" },
    { plate: "NRU", district: "Neustadt am Rübenberge, Dolna Saksonia" },
    {
      plate: "NRW",
      district: "pojazdy administracji landu Nadrenia Północna-Westfalia",
    },
    { plate: "NU", district: "Neu-Ulm, Bawaria" },
    { plate: "NT", district: "Nürtingen, Badenia-Wirtembergia" },
    { plate: "NVP", district: "Nordvorpommern, Meklemburgia-Pomorze Przednie" },
    { plate: "NW", district: "Neustadt an der Weinstraße, Nadrenia-Palatynat" },
    {
      plate: "NWM",
      district: "Nordwestmecklenburg, Meklemburgia-Pomorze Przednie",
    },
    { plate: "NY", district: "Niesky, Saksonia" },
    { plate: "NZ", district: "Neustrelitz, Meklemburgia-Pomorze Przednie" },
    { plate: "OA", district: "Oberallgäu, Bawaria" },
    { plate: "OAL", district: "Ostallgäu, Bawaria" },
    { plate: "OB", district: "Oberhausen, Nadrenia Północna-Westfalia" },
    { plate: "OBB", district: "Obernburg, Bawaria" },
    { plate: "OBG", district: "Osterburg, Saksonia-Anhalt" },
    { plate: "OC", district: "Oschersleben, Saksonia" },
    { plate: "OCH", district: "Ochsenfurt, Bawaria" },
    { plate: "OD", district: "Bad Oldesloe i Stormarn, Szlezwik-Holsztyn" },
    { plate: "OE", district: "Olpe, Nadrenia Północna-Westfalia" },
    { plate: "OF", district: "Offenbach am Main, Hesja" },
    { plate: "OG", district: "Offenburg i Ortenaukreis, Badenia-Wirtembergia" },
    { plate: "OH", district: "Ostholstein, Szlezwik-Holsztyn" },
    { plate: "OHA", district: "Osterode am Harz, Dolna Saksonia" },
    { plate: "OHR", district: "Ohringen, Badenia-Wirtembergia" },
    { plate: "OHV", district: "Oberhavel, Brandenburgia" },
    { plate: "OHZ", district: "Osterholz, Dolna Saksonia" },
    { plate: "OK", district: "Ohre-Kreis, Saksonia-Anhalt" },
    { plate: "OL", district: "Oldenburg, Dolna Saksonia" },
    { plate: "OLD", district: "Oldenburg (Holstein), Szlezwik-Holsztyn" },
    { plate: "OP", district: "Opladen, Nadrenia Północna-Westfalia" },
    { plate: "OPR", district: "Ostprignitz-Ruppin, Brandenburgia" },
    { plate: "OR", district: "Oranienburg, Brandenburgia" },
    { plate: "OS", district: "Osnabrück, Dolna Saksonia" },
    { plate: "OSL", district: "Oberspreewald-Lausitz, Brandenburgia" },
    { plate: "OTT", district: "Otterndorf, Dolna Saksonia" },
    { plate: "OTW", district: "Ottweiler, Saara" },
    { plate: "OVI", district: "Oberviechtach, Bawaria" },
    { plate: "OVL", district: "Obervogtland, Saksonia" },
    { plate: "OVP", district: "Ostvorpommern, Meklemburgia-Pomorze Przednie" },
    { plate: "OZ", district: "Oschatz, Saksonia" },
    { plate: "P", district: "Poczdam, Brandenburgia" },
    { plate: "PA", district: "Passau, Bawaria" },
    { plate: "PAF", district: "Pfaffenhofen an der Ilm, Bawaria" },
    { plate: "PAN", district: "Pfarrkirchen i Rottal-Inn, Bawaria" },
    { plate: "PAR", district: "Parsberg, Bawaria" },
    { plate: "PB", district: "Paderborn, Nadrenia Północna-Westfalia" },
    { plate: "PCH", district: "Parchim, Meklemburgia-Pomorze Przednie" },
    { plate: "PE", district: "Peine, Dolna Saksonia" },
    { plate: "PEG", district: "Pegnitz, Bavraia" },
    { plate: "PER", district: "Perleberg, Brandenburgia" },
    { plate: "PF", district: "Pforzheim i Enzkreis, Badenia-Wirtembergia" },
    { plate: "PI", district: "Pinneberg, Szlezwik-Holsztyn" },
    { plate: "PIR", district: "Pirna, Saksonia" },
    { plate: "PK", district: "Pritzwalk, Brandenburgia" },
    { plate: "PL", district: "Plauen, Saksonia" },
    { plate: "PLO", district: "Plön, Szlezwik-Holsztyn" },
    { plate: "PM", district: "Potsdam-Mittelmark, Brandenburgia" },
    { plate: "PN", district: "Pößneck, Turyngia" },
    { plate: "PR", district: "Prignitz, Brandenburgia" },
    { plate: "PRU", district: "Prüm, Nadrenia-Palatynat" },
    { plate: "PS", district: "Pirmasens i Südwestpfalz, Nadrenia-Palatynat" },
    { plate: "PW", district: "Pasewalk, Meklemburgia-Pomorze Przednie" },
    { plate: "PZ", district: "Prenzlau, Brandenburgia" },
    { plate: "QFT", district: "Querfurt, Saksonia-Anhalt" },
    { plate: "QLB", district: "Quedlinburg, Saksonia-Anhalt" },
    { plate: "R", district: "Regensberg, Bawaria" },
    { plate: "RA", district: "Ratstatt, Badenia-Wirtembergia" },
    { plate: "RC", district: "Reichenbach, Saksonia" },
    { plate: "RD", district: "Rendsburg-Eckernförde, Szlezwik-Holsztyn" },
    {
      plate: "RDG",
      district: "Ribnitz-Damgarten, Meklemburgia-Pomorze Przednie",
    },
    { plate: "RE", district: "Recklinghausen, Nadrenia Północna-Westfalia" },
    { plate: "REG", district: "Regen, Bawaria" },
    { plate: "REH", district: "Rehau, Bawaria" },
    { plate: "REI", district: "Bad Reichenhall, Bawaria" },
    { plate: "RG", district: "Riesa-Großenhain, Saksonia" },
    { plate: "RH", district: "Roth bei Nürnberg, Bawaria" },
    { plate: "RI", district: "Rinteln, Dolna Saksonia" },
    { plate: "RID", district: "Riedenburg, Bawaria" },
    { plate: "RIE", district: "Riesa, Saksonia" },
    { plate: "RL", district: "Rochlitz, Saksonia" },
    { plate: "RM", district: "Röbel/Muritz, Meklemburgia-Pomorze Przednie" },
    { plate: "RN", district: "Rathenow, Brandenburgia" },
    { plate: "RO", district: "Rosenheim, Bawaria" },
    { plate: "ROD", district: "Roding, Bawaria" },
    { plate: "ROF", district: "Rotenburg bei Fulda, Hesja" },
    { plate: "ROH", district: "Rotenburg Wümme, Dolna Saksonia" },
    { plate: "ROK", district: "Rockenhausen, Nadrenia-Palatynat" },
    { plate: "ROL", district: "Rottenburg Laaber, Bawaria" },
    { plate: "ROS", district: "Rostock Land, Meklemburgia-Pomorze Przednie" },
    { plate: "ROT", district: "Rothenburg ob der Tauber, Bawaria" },
    {
      plate: "ROW",
      district: "Rotenburg (Wümme) i Bremervörde, Dolna Saksonia",
    },
    {
      plate: "RPL",
      district: "pojazdy administracji landu Nadrenia-Palatynat",
    },
    { plate: "RS", district: "Remscheid, Nadrenia Północna-Westfalia" },
    { plate: "RSL", district: "Roßlau, Saksonia-Anhalt" },
    { plate: "RT", district: "Reutlingen, Badenia-Wirtembergia" },
    { plate: "RU", district: "Rudolstadt" },
    { plate: "RUD", district: "Rüdesheim i Rheingau-Taunus-Kreis, Hesja" },
    { plate: "RUG", district: "Rügen, Meklemburgia-Pomorze Przednie" },
    { plate: "RV", district: "Ravensburg, Badenia-Wirtembergia" },
    { plate: "RW", district: "Rottweil, Badenia-Wirtembergia" },
    {
      plate: "RWL",
      district: "pojazdy administracji landu Nadrenia Północna-Westfalia",
    },
    { plate: "RY", district: "Rheydt, Nadrenia Północna-Westfalia" },
    {
      plate: "RZ",
      district: "Ratzeburg i Hertzogtum Lauenburg, Szlezwik-Holsztyn",
    },
    { plate: "S", district: "Stuttgart, Badenia-Wirtembergia" },
    { plate: "SAB", district: "Saarburg, Nadrenia-Palatynat" },
    { plate: "SAD", district: "Schwandorf, Bawaria" },
    { plate: "SAK", district: "Säckingen, Badenia-Wirtembergia" },
    { plate: "SAL", district: "pojazdy administracji landu Saara" },
    { plate: "SAN", district: "Stadtsteinach, Bawaria" },
    { plate: "SAO", district: "Saale-Orla Kreis" },
    { plate: "SAW", district: "Altmarkkreis Salzwedel, Saksonia-Anhalt" },
    { plate: "SB", district: "Saarbrücken, Saara" },
    { plate: "SBG", district: "Strasburg, Meklemburgia-Pomorze Przednie" },
    { plate: "SBK", district: "Schönebeck, Saksonia-Anhalt" },
    { plate: "SC", district: "Schwabach, Bawaria" },
    { plate: "SCZ", district: "Schleiz, Turyngia" },
    { plate: "SDH", district: "Sondershausen, Turyngia" },
    { plate: "SDL", district: "Stendal, Saksonia-Anhalt" },
    { plate: "SDT", district: "Schwedt, Brandenburgia" },
    { plate: "SE", district: "Segeberg, Szlezwik-Holsztyn" },
    { plate: "SEB", district: "Sebnitz, Saksonia" },
    { plate: "SEE", district: "Seelow, Brandenburgia" },
    { plate: "SEF", district: "Scheinfeld, Bawaria" },
    { plate: "SEL", district: "Selb, Bawaria" },
    { plate: "SF", district: "Sonthofen, Bawaria" },
    { plate: "SFA", district: "Soltau-Fallingbostel, Dolna Saksonia" },
    { plate: "SFB", district: "Senftenberg, Brandenburgia" },
    { plate: "SFT", district: "Staßfurt, Saksonia-Anhalt" },
    { plate: "SG", district: "Solingen, Nadrenia Północna-Westfalia" },
    { plate: "SGH", district: "Sangerhausen, Saksonia-Anhalt" },
    { plate: "SH", district: "pojazdy administracji landu Szlezwik-Holsztyn" },
    { plate: "SHA", district: "Schwäbisch Hall, Badenia-Wirtembergia" },
    { plate: "SHG", district: "Stadthagen i Schaumburg, Dolna Saksonia" },
    { plate: "SHK", district: "Saale-Holzland-Kreis, Turyngia" },
    { plate: "SHL", district: "Suhl, Turyngia" },
    { plate: "SHS", district: "Sangerhausen" },
    {
      plate: "SI",
      district: "Siegen-Wittgenstein, Nadrenia Północna-Westfalia",
    },
    { plate: "SIG", district: "Sigmaringen, Badenia-Wirtembergia" },
    {
      plate: "SIM",
      district: "Simmern i Rhein-Hunsrück-Kreis, Nadrenia-Palatynat",
    },
    { plate: "SK", district: "Saalkreis, Saksonia-Anhalt" },
    { plate: "SL", district: "Schleswig-Flensburg, Szlezwik-Holsztyn" },
    {
      plate: "SLE",
      district: "Schleiden (Eifel), Nadrenia Północna-Westfalia",
    },
    { plate: "SLF", district: "Saalfeld-Rudolstadt, Turyngia" },
    { plate: "SLG", district: "Saulgau, Badenia-Wirtembergia" },
    { plate: "SLN", district: "Schmölin, Turyngia" },
    { plate: "SLS", district: "Saarlouis, Saara" },
    { plate: "SLU", district: "Schlüchtern, Hesja" },
    { plate: "SLZ", district: "Bad Salzungen, Turyngia" },
    { plate: "SM", district: "Schmalkalden-Meiningen, Turyngia" },
    { plate: "SMU", district: "Schwabmünchen, Bawaria" },
    { plate: "SN", district: "Schwerin, Meklemburgia-Pomorze Przednie" },
    { plate: "SNH", district: "Sinsheim, Badenia-Wirtembergia" },
    { plate: "SO", district: "Soest, Nadrenia Północna-Westfalia" },
    { plate: "SOB", district: "Schrobenhausen, Bawaria" },
    { plate: "SOG", district: "Schongau, Bawaria" },
    { plate: "SOK", district: "Saale-Orla-Kreis, Turyngia" },
    { plate: "SOL", district: "Soltau, Dolna Saksonia" },
    { plate: "SOM", district: "Sömmerda, Turyngia" },
    { plate: "SON", district: "Sonneberg, Turyngia" },
    { plate: "SP", district: "Speyer, Nadrenia-Palatynat" },
    { plate: "SPB", district: "Spremberg, Brandenburgia" },
    { plate: "SPN", district: "Spree-Neiße, Brandenburgia" },
    { plate: "SPR", district: "Springe, Dolna Saksonia" },
    { plate: "SR", district: "Straubing i Straubing-Bogen, Bawaria" },
    { plate: "SRB", district: "Strausberg, Brandenburgia" },
    { plate: "SRO", district: "Stadtroda, Turyngia" },
    { plate: "ST", district: "Steinfurt, Nadrenia Północna-Westfalia" },
    { plate: "STA", district: "Starnberg, Bawaria" },
    { plate: "STB", district: "Sternberg, Meklemburgia-Pomorze Przednie" },
    { plate: "STD", district: "Stade, Dolna Saksonia" },
    { plate: "STE", district: "Staffelstein, Bawaria" },
    { plate: "STH", district: "Stadthagen, Dolna Saksonia" },
    { plate: "STL", district: "Stollberg, Saksonia" },
    { plate: "STO", district: "Stockach, Badenia-Wirtembergia" },
    {
      plate: "SU",
      district: "Siegburg i Rhein-Sieg-Kreis, Nadrenia Północna-Westfalia",
    },
    { plate: "SUL", district: "Sulzbach-Rosenberg, Bawaria" },
    { plate: "SUW", district: "Südliche Weinstraße, Nadrenia-Palatynat" },
    { plate: "SW", district: "Schweinfurt, Bawaria" },
    { plate: "SWA", district: "Bad Schwalbach i Rheingau-Taunus-Kreis, Hesja" },
    { plate: "SWZ", district: "Schwarzakreis" },
    { plate: "SY", district: "Syke, Dolna Saksonia" },
    { plate: "SZ", district: "Salzgitter, Dolna Saksonia" },
    { plate: "SZB", district: "Schwarzenberg, Saksonia" },
    {
      plate: "TBB",
      district: "Tauberbischofsheim i Main-Tauber-Kreis, Badenia-Wirtembergia",
    },
    { plate: "TE", district: "Teterow, Meklemburgia-Pomorze Przednie" },
    { plate: "TF", district: "Teltow-Fläming, Brandenburgia" },
    { plate: "TG", district: "Torgau, Saksonia" },
    { plate: "TGO", district: "Thurgau-Oschatz" },
    { plate: "THL", district: "pojazdy administracji landu Turyngia" },
    {
      plate: "THW",
      district: "pojazdy administracji federalnej agencji pomocy technicznej",
    },
    { plate: "TIR", district: "Tirschenreuth, Bawaria" },
    { plate: "TO", district: "Torgau-Oschatz, Saksonia" },
    { plate: "TOL", district: "Bad Tölz-Wolfratshausen, Bawaria" },
    { plate: "TON", district: "Tönning, Szlezwik-Holsztyn" },
    { plate: "TP", district: "Templin, Brandenburgia" },
    { plate: "TR", district: "Trier, Nadrenia-Palatynat" },
    { plate: "TS", district: "Traunstein, Bawaria" },
    { plate: "TT", district: "Tettnang, Badenia-Wirtembergia" },
    { plate: "TU", district: "Tübingen, Badenia-Wirtembergia" },
    { plate: "TUT", district: "Tuttlingen, Badenia-Wirtembergia" },
    { plate: "UB", district: "Uberlingen, Badenia-Wirtembergia" },
    { plate: "UE", district: "Uelzen, Dolna Saksonia" },
    { plate: "UEM", district: "Ueckermünde, Meklemburgia-Pomorze Przednie" },
    { plate: "UER", district: "Uecker-Randow, Meklemburgia-Pomorze Przednie" },
    { plate: "UFF", district: "Uffenheim, Bawaria" },
    { plate: "UH", district: "Unstrut-Hainich, Turyngia" },
    { plate: "UL", district: "Ulm i Alb-Donau-Kreis, Badenia-Wirtembergia" },
    { plate: "UM", district: "Uckermark, Brandenburgia" },
    { plate: "UN", district: "Unna, Nadrenia Północna-Westfalia" },
    { plate: "USI", district: "Usingen, Hesja" },
    { plate: "V", district: "Vogtlandkreis, Saksonia" },
    { plate: "VAI", district: "Vaihingen, Badenia-Wirtembergia" },
    { plate: "VB", district: "Vogelsbergkreis, Hesja" },
    { plate: "VEC", district: "Vechta, Dolna Saksonia" },
    { plate: "VER", district: "Verden, Dolna Saksonia" },
    { plate: "VIB", district: "Vilsbiburg, Bawaria" },
    { plate: "VIE", district: "Viersen, Nadrenia Północna-Westfalia" },
    { plate: "VIT", district: "Viechtach, Bawaria" },
    { plate: "VK", district: "Völklingen, Saara" },
    { plate: "VL", district: "Villingen, Badenia-Wirtembergia" },
    { plate: "VOF", district: "Vilshofen, Bawaria" },
    { plate: "VOH", district: "Vohenstrauß, Bawaria" },
    {
      plate: "VS",
      district:
        "Villingen-Schwenningen i Schwarzwald-Baar-Kreis, Badenia-Wirtembergia",
    },
    { plate: "W", district: "Wuppertal, Nadrenia Północna-Westfalia" },
    { plate: "WA", district: "Waldeck, Hesja" },
    { plate: "WAF", district: "Kreis Warendorf, Nadrenia Północna-Westfalia" },
    { plate: "WAK", district: "Wartburgkreis, Turyngia" },
    { plate: "WAM", district: "Westliche Altmark" },
    { plate: "WAN", district: "Wanne-Eickel, Nadrenia Północna-Westfalia" },
    { plate: "WAR", district: "Warburg, Nadrenia Północna-Westfalia" },
    { plate: "WAT", district: "Wattenscheid, Nadrenia Północna-Westfalia" },
    { plate: "WB", district: "Wittenberga, Saksonia-Anhalt" },
    { plate: "WBS", district: "Worbis, Turyngia" },
    { plate: "WD", district: "Weidenbrück, Nadrenia Północna-Westfalia" },
    { plate: "WDA", district: "Werdau, Saksonia" },
    { plate: "WE", district: "Weimar, Turyngia" },
    { plate: "WEB", district: "Westerburg, Nadrenia-Palatynat" },
    { plate: "WEG", district: "Wegscheid, Bawaria" },
    { plate: "WEI", district: "Weimarer Land (Kreis Apolda)" },
    { plate: "WEL", district: "Weilburg, Hesja" },
    { plate: "WEM", district: "Wesermünde, Dolna Saksonia" },
    { plate: "WEN", district: "Weiden in der Oberpfalz, Bawaria" },
    { plate: "WER", district: "Wertingen, Bawaria" },
    { plate: "WES", district: "Wesel, Nadrenia Północna-Westfalia" },
    { plate: "WF", district: "Wolfenbüttel, Dolna Saksonia" },
    { plate: "WG", district: "Wangen, Badenia-Wirtembergia" },
    { plate: "WHV", district: "Wilhelmshaven, Dolna Saksonia" },
    { plate: "WI", district: "Wiesbaden, Hesja" },
    {
      plate: "WIL",
      district: "Wittlich i Bernkastel-Wittlich, Nadrenia-Palatynat",
    },
    { plate: "WIS", district: "Wismarer Land" },
    { plate: "WIT", district: "Witten, Nadrenia Północna-Westfalia" },
    { plate: "WIZ", district: "Witzenhausen, Hesja" },
    { plate: "WK", district: "Wittstock, Brandenburgia" },
    { plate: "WL", district: "Winsen (Luhe) i Harburg, Dolna Saksonia" },
    { plate: "WLG", district: "Wolgast, Meklemburgia-Pomorze Przednie" },
    { plate: "WM", district: "Weilheim-Schongau, Bawaria" },
    { plate: "WMS", district: "Wolmirstedt, Saksonia-Anhalt" },
    {
      plate: "WN",
      district: "Waiblingen i Rems-Murr-Kreis, Badenia-Wirtembergia",
    },
    { plate: "WND", district: "St Wendel, Saara" },
    { plate: "WO", district: "Worms, Nadrenia-Palatynat" },
    { plate: "WOB", district: "Wolfsburg, Dolna Saksonia" },
    { plate: "WOH", district: "Wolfhagen, Hesja" },
    { plate: "WOL", district: "Wolfach, Badenia-Wirtembergia" },
    { plate: "WOR", district: "Wolfratshausen, Bawaria" },
    { plate: "WOS", district: "Wolfstein, Bawaria" },
    { plate: "WR", district: "Wernigerode, Saksonia-Anhalt" },
    { plate: "WRN", district: "Waren, Meklemburgia-Pomorze Przednie" },
    { plate: "WS", district: "Wasserburg, Bawaria" },
    { plate: "WSF", district: "Weißenfels, Saksonia-Anhalt" },
    { plate: "WST", district: "Westerstede i Ammerland, Dolna Saksonia" },
    { plate: "WSW", district: "Weißwasser, Saksonia" },
    { plate: "WT", district: "Waldshut, Badenia-Wirtembergia" },
    { plate: "WTL", district: "Wittlage, Dolna Saksonia" },
    { plate: "WTM", district: "Wittmund, Dolna Saksonia" },
    { plate: "WU", district: "Würzburg, Bawaria" },
    { plate: "WUG", district: "Weißenburg-Gunzenhausen, Bawaria" },
    { plate: "WUM", district: "Waldmünchen, Bawaria" },
    { plate: "WUN", district: "Wunsiedel am Fichtelgebirge, Bawaria" },
    { plate: "WUR", district: "Wurzen, Saksonia" },
    { plate: "WW", district: "Westerwaldkreis, Nadrenia-Palatynat" },
    { plate: "WZ", district: "Wetzlar, Hesja" },
    { plate: "WZL", district: "Wanzleben, Saksonia-Anhalt" },
    { plate: "X", district: "pojazdy sił zbrojnych NATO" },
    { plate: "Y", district: "pojazdy niemieckich sił zbrojnych" },
    { plate: "Z", district: "Zwickauer Land, Saksonia" },
    { plate: "ZE", district: "Zerbst, Saksonia-Anhalt" },
    { plate: "ZEL", district: "Zell, Nadrenia-Palatynat" },
    { plate: "ZI", district: "Löbau-Zittau, Saksonia" },
    { plate: "ZIG", district: "Ziegenhain, Hesja" },
    { plate: "ZP", district: "Zschopau, Saksonia" },
    { plate: "ZR", district: "Zeulenroda, Turyngia" },
    { plate: "ZS", district: "Zossen, Brandenburgia" },
    { plate: "ZW", district: "Zweibrücken, Nadrenia-Palatynat" },
    { plate: "ZZ", district: "Zeitz, Saksonia-Anhalt" },
  ],
};
